name: api_server
description: A web server application.
version: 0.0.1
author: Alois Deniel

environment:
  sdk: '>=1.20.0 <2.0.0'

dependencies:
  aqueduct: ^2.5.0+1
  api_messages:
    path: ../api_messages

dev_dependencies:
  test: '>=0.12.0 <0.13.0'